[package]

name = "iron_kaleidoscope"
version = "0.0.1"
authors = ["Jauhien Piatlicki <jauhien@gentoo.org>"]

[dependencies]
docopt = "0.6"
regex = "*"

rustc-serialize = "0.3"
llvm-sys = "0.2.1"

[dependencies.iron_llvm]
path = "../../iron-llvm"
