[package]

name = "iron_kaleidoscope"
version = "0.0.1"
authors = ["Jauhien Piatlicki <jauhien@gentoo.org>"]

[dependencies]
docopt = "0.6"
llvm-sys = "0.2.1"
regex = "*"
regex_macros = "*"
rustc-serialize = "0.3"

[dependencies.iron_llvm]
git = "https://github.com/jauhien/iron-llvm.git"
